spring:
  application:
    name: Dhanush-2Greet
  boot:
    admin:
      client:
        url: http://localhost:9095
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: '*'
